import Foundation

enum AirportPolicyFileStore {
    private static let generatedMarker = "# Generated by Surge Relay; subscription-id="

    static func fileNames(for subscriptions: [AirportSubscription]) -> [UUID: String] {
        let grouped = Dictionary(grouping: subscriptions) { subscription in
            sanitizedBaseName(subscription.trimmedName).lowercased()
        }
        var result: [UUID: String] = [:]
        for subscription in subscriptions {
            let base = sanitizedBaseName(subscription.trimmedName)
            let duplicates = grouped[base.lowercased(), default: []].count > 1
            let suffix = duplicates ? "-\(subscription.id.uuidString.prefix(8).lowercased())" : ""
            result[subscription.id] = "\(base)\(suffix).proxies"
        }
        return result
    }

    static func relativePath(fileName: String) -> String {
        fileName
    }

    static func content(subscriptionID: UUID, entries: [ProcessedAirportProxyEntry]) -> String {
        let lines = entries.map { "\($0.name) = \($0.definition)" }
        return (["\(generatedMarker)\(subscriptionID.uuidString.lowercased())"] + lines)
            .joined(separator: "\n") + "\n"
    }

    static func write(
        files: [String: String],
        beside configurationURL: URL
    ) throws {
        let directory = configurationURL.deletingLastPathComponent()

        for (fileName, content) in files {
            try Data(content.utf8).write(to: directory.appending(path: fileName), options: .atomic)
        }

        let expected = Set(files.keys)
        let existing = try FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        )
        for url in existing where isPolicyFile(url.lastPathComponent) && !expected.contains(url.lastPathComponent) {
            guard let data = try? Data(contentsOf: url),
                  let prefix = String(data: Data(data.prefix(256)), encoding: .utf8),
                  prefix.hasPrefix(generatedMarker) else { continue }
            try FileManager.default.removeItem(at: url)
        }
    }

    private static func isPolicyFile(_ fileName: String) -> Bool {
        fileName.hasSuffix(".proxies") || fileName.hasSuffix(".proxies.txt")
    }

    private static func sanitizedBaseName(_ value: String) -> String {
        let forbidden = CharacterSet(charactersIn: "/\\:*?\"<>|")
            .union(.controlCharacters)
        let base = value.components(separatedBy: forbidden)
            .joined(separator: "-")
            .replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: ".- "))
        return base.isEmpty ? "Airport" : String(base.prefix(80))
    }
}
